name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
      # 1. Télécharger le code
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Vérifier Docker
      - name: Check Docker version
        run: docker --version

      # 3. Build backend
      - name: Build Backend Image
        run: docker build -t backend ./backend

      # 4. Build frontend
      - name: Build Frontend Image
        run: docker build -t frontend ./frontend


      - name: Run simple test
        run: echo "Tests OK "

      - name: Run application
        run: docker compose up -d --build

      - name: Check containers
        run: docker ps
