name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Check Docker version
        run: docker --version

      - name: Build Backend Image
        run: docker build -t backend ./backend

      - name: Build Frontend Image
        run: docker build -t frontend ./frontend

      - name: Run simple test
        run: echo "Tests OK "

      - name: Run application
        run: docker compose up -d --build

      - name: Check containers
        run: docker ps
